spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:study-security
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug